name: issue_reminder

# 스케줄 실행
on:
  schedule:
    - cron: "30 10 * * 1,2,3,4,5" # 주중 10시 반에 실행

# 깃허브 액션 수동 실행
#on:
#  workflow_dispatch:
#    inputs:
#      logLevel:
#        description: 'Log level'
#        required: true
#        default: 'warning'
#        type: choice
#        options:
#        - info
#        - warning
#        - debug
#      tags:
#        description: 'Test scenario tags'
#        required: false
#        type: boolean
#      environment:
#        description: 'Environment to run tests against'
#        type: environment
#        required: true

jobs:
  issue-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install
      - run: npm start
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GIT_TOKEN }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      

